//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgramm
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyzesTable
    {
        public int AnalyzeID { get; set; }
        public string Name { get; set; }
        public string NormValue { get; set; }
        public int Cost { get; set; }
    }
}
