//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgramm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsTable
    {
        public int ContractID { get; set; }
        public System.DateTime ContractDate { get; set; }
        public bool IsActive { get; set; }
    }
}
