//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgramm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBConnection : DbContext
    {
        public DBConnection()
            : base("name=DBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PermissionTable> PermissionTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<GlobalEventsTable> GlobalEventsTable { get; set; }
        public virtual DbSet<ServicesTable> ServicesTable { get; set; }
        public virtual DbSet<ContractsTable> ContractsTable { get; set; }
        public virtual DbSet<ClientsTable> ClientsTable { get; set; }
        public virtual DbSet<AnalyzesTable> AnalyzesTable { get; set; }
        public virtual DbSet<ServicesAnalyzesTable> ServicesAnalyzesTable { get; set; }
        public virtual DbSet<ResultsTable> ResultsTable { get; set; }
        public virtual DbSet<UsersTable> UsersTable { get; set; }
        public virtual DbSet<OrdersTable> OrdersTable { get; set; }
    }
}
