//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgramm
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public int OrderID { get; set; }
        public int ClientID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> ResultID { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime DateComeIn { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public bool SendEmail { get; set; }
    }
}
