//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgramm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsTable
    {
        public int ResultID { get; set; }
        public int AnalyzeID { get; set; }
        public string Result { get; set; }
        public string ResultFileName { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
