//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProgramm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesAnalyzesTable
    {
        public int IDService { get; set; }
        public int IDAnalyze { get; set; }
    }
}
